sudo: required
language: ruby
services:
  - docker
git:
  depth: 4

# whitelist
branches:
  only:
    - jekyll

before_install:
 - sudo apt-get  -qq  update
 - sudo apt-get install zlib1g-dev
 - gem update --no-rdoc --no-ri
 - gem cleanup --dryrun
 - gem uninstall addressable -aIx
 - gem install addressable:2.4.0 --no-rdoc --no-ri
 - gem install  --no-rdoc --no-ri bundler io-console
 - gem install jekyll            --no-rdoc --no-ri
 - gem install jekyll-sitemap    --no-rdoc --no-ri
 - gem install jekyll-gist       --no-rdoc --no-ri
 - gem install jekyll-paginate   --no-rdoc --no-ri
 - gem install rdiscount         --no-rdoc --no-ri
 - gem install  pygments.rb:0.5.0  compass --no-rdoc --no-ri
 - gem install jekyll-minifier    --no-rdoc --no-ri
 - gem install jekyll-seo-tag     --no-rdoc --no-ri
 - gem install jekyll-auto-image  --no-rdoc --no-ri


script:
 - jekyll build --profile --incremental --source blog/ --destination Blog
 - make build start logs

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - TIMEOUT=1000
