sudo: required
language: ruby
services:
  - docker
git:
  depth: 4

# whitelist
branches:
  only:
    - jekyll

before_install:
 - sudo apt-get  -qq  update
 - gem update                    --no-rdoc --no-ri
 - gem install jekyll            --no-rdoc --no-ri
 - gem install jekyll-sitemap    --no-rdoc --no-ri
 - gem install jekyll-gist       --no-rdoc --no-ri
 - gem install jekyll-paginate   --no-rdoc --no-ri
 - gem install rdiscount         --no-rdoc --no-ri
 - gem install  pygments.rb:0.5.0  compass --no-rdoc --no-ri


script:
 - jekyll build --incremental --source earvin/blog/ --destination Blog
 - make build start logs

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - TIMEOUT=1000
