sudo: required
services:
  - docker
# whitelist
branches:
  only:
    - jekyll

script:
 - docker build -t earvin/blog .
 - docker images -a
# - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
