language: ruby
matrix:
  include:
    - os: linux
      dist: trusty
rvm:
- 2.1
# whitelist
branches:
  only:
    - jekyll
before_install:
  - gem update --system
  - gem --version
install: gem install jekyll html-proofer
script: cd earvin; ls && (jekyll build && htmlproofer ./_site)

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
