source 'https://rubygems.org'
gem 'io-console'
gem 'rspec'
gem 'jekyll'
gem 'jekyll-sitemap'
gem 'jekyll-gist'
gem 'jekyll-paginate'
gem 'json'
gem 'format'
gem 'bigdecimal'
gem 'jekyll-minifier'
gem 'jekyll-seo-tag'
gem 'rdiscount'
group :jekyll_plugins do
  gem 'jekyll_pages_api'
end
