# top level stuff you probably don't need to touch
highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 10
port: 3000
#safe: true
gems:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-minifier
  - jekyll-seo-tag
  - jekyll-auto-image

jekyll-minifier:
    exclude: 'atom.xml'

collections:
  notes:
    output: true
    permalink: /notes/:title.html
# edit here to achieve your personal greatness
url: https://www.earvinkayonga.com #localhost:3000
baseurl: /
title: Earvin Kayonga's Tech Blog
author: Earvin Kayonga
description:  This is Earvin Kayonga's blog on stuff he does on the Web as a Software engineer.
avatar: photo.jpg
email: earvin[at]earvinkayonga.com
resume: /vitae/
github: earvinkayonga # username
twitter: EarvinKayonga
linkedin: earvinkayonga
stackoverflow: users/4990466/papimartial
image: https://www.earvinkayonga.com/static/img/profile.png
#Comment out if you don't want disqus
#disqus: earvinkayonga
google_analytics: UA-76175245-1


# needed for travis-ci build
exclude: [vendor]
