# top level stuff you probably don't need to touch
highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
port: 3000
#safe: true
gems:
  - jekyll-gist
  - jekyll-paginate

# edit here to achieve your personal greatness
url: https://www.earvinkayonga.com #localhost:3000
baseurl: /
title: Earvin Kayonga's Tech Blog
author: Earvin Kayonga
description:  This is Earvin Kayonga's Tech blog with his resume and links to his activities on the Web as a Software engineer.
avatar: photo.jpg
email: earvin[at]earvinkayonga.com
resume: /vitae/
github: earvinkayonga # username
twitter: EarvinKayonga
linkedin: earvinkayonga
stackoverflow: users/4990466/papimartial
#Comment out if you don't want disqus
#disqus: earvinkayonga
google_analytics: UA-76175245-1


# needed for travis-ci build
exclude: [vendor]
